### ISSUE TITLE
AttributeError: module 'pypath' has no attribute 'resources' 

### ISSUE THREAD

**Issue by CPerscheid** [saezlab/pypath#157]
Hi there, 
I have installed a fresh version of pypath on an Ubuntu, however I get the error below when trying to import pypath.core.network. I do not get the error on another machine with pypath version 0.11.32. Please help!

```
>>> import pypath.core.network as network

        === d i s c l a i m e r ===

        All data accessed through this module,
        either as redistributed copy or downloaded using the
        programmatic interfaces included in the present module,
        are free to use at least for academic research or
        education purposes.
        Please be aware of the licenses of all the datasets
        you use in your analysis, and please give appropriate
        credits for the original sources when you publish your
        results. To find out more about data sources please
        look at `src/pypath/resources/data/resources.json` or
        https://omnipathdb.org/info and 
        `pypath.resources.urls.urls`.

[2020-10-13 15:54:46] [pypath] 
        - session ID: `rok9u`
        - working directory: `/home/xx`
        - logfile: `/home/xx/pypath_log/pypath-rok9u.log`
        - pypath version: 0.11.34
[2020-10-13 15:54:47] [curl] Module `pysftp` not available. Only downloading of a small number of resources relies on this module. Please install by PIP if it is necessary for you.
[2020-10-13 15:54:47] [curl] Module `fabric` not available.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pypath/core/network.py", line 39, in <module>
    import pypath.core.interaction as interaction_mod
  File "/usr/local/lib/python3.6/dist-packages/pypath/core/interaction.py", line 38, in <module>
    import pypath.core.evidence as pypath_evidence
  File "/usr/local/lib/python3.6/dist-packages/pypath/core/evidence.py", line 36, in <module>
    import pypath.internals.refs as refs
  File "/usr/local/lib/python3.6/dist-packages/pypath/internals/refs.py", line 34, in <module>
    import pypath.resources.urls as urls
  File "/usr/local/lib/python3.6/dist-packages/pypath/resources/__init__.py", line 22, in <module>
    from pypath.resources import controller as _controller_mod
  File "/usr/local/lib/python3.6/dist-packages/pypath/resources/controller.py", line 32, in <module>
    import pypath.resources.licenses as licenses
AttributeError: module 'pypath' has no attribute 'resources'
```

**Comment by deeenes** [comment]
Hi,

This happened due to some import loops that Python 3.8 can handle but 3.6 couldn't yet.
Thanks for finding it, I don't test often in Py3.6

Best,

Denes

**Comment by CPerscheid** [comment]
Hi Denes,
so has the bug been resolved and I just need to update pypath with pip, or do I have to upgrade to Python 3.8 instead?
Best,
Cindy

**Comment by deeenes** [comment]
Hi Cindy,

Yes I fixed it in fd3f736 (pypath 0.11.37), should work with Py 3.6.
Though keeping your Python up to date is always a good idea :)

Best,

Denes

**Comment by CPerscheid** [comment]
> Though keeping your Python up to date is always a good idea :)
But who would test pypath in 3.6 for you then? ;)

Thanks a lot, it works fine now. :)
